setwd("/Volumes/Disco2024/Papers/EnPreparacion/DProtein/2024/EAAInProteinsAndMetabolism/DataFiguresPaper/Figure2")

par(mfrow=c(2,2))

data1=read.delim("dataFigure2-1.csv", head=TRUE, sep=",")
attach(data1)

plot(time,Ala,xlab="Hours",ylab="mg/L", col="blue", ylim=c(0,600))
l1=c(paste0('                                         Intracellular\n','-NaCl'))
mtext(l1, side=3, line=0, cex=1.5, font=3)
points(time,Asp, pch=1, col="blue")
points(time,Glu, pch=1, col="blue")
points(time,Gln, pch=1, col="blue")
points(time,Ser, pch=1, col="blue")
points(time,Ala, pch=1, col="blue")
points(time,Gly, pch=1, col="blue")
points(time,Arg, pch=1, col="blue")

points(time,His, pch=0, col="red")
points(time,Ile, pch=0, col="red")
points(time,Leu, pch=0, col="red")
points(time,Lys, pch=0, col="red")
points(time,Met, pch=0, col="red")
points(time,Cys, pch=0, col="red")
points(time,Phe, pch=0, col="red")
points(time,Thr, pch=0, col="red")
points(time,Tyr, pch=0, col="red")
points(time,Val, pch=0, col="red")

points(time,Ammonia, pch=2, col="green")

data2=read.delim("dataFigure2-2.csv", head=TRUE, sep=",")
attach(data2)

plot(time,Ala,xlab="Hours",ylab="mg/L", col="blue", ylim=c(0,600))
l2=c(paste0('\n','+NaCl'))
mtext(l2, side=3, line=0, cex=1.5, font=3)

points(time,Asp, pch=1, col="blue")
points(time,Glu, pch=1, col="blue")
points(time,Gln, pch=1, col="blue")
points(time,Ser, pch=1, col="blue")
points(time,Ala, pch=1, col="blue")
points(time,Gly, pch=1, col="blue")
points(time,Arg, pch=1, col="blue")

points(time,His, pch=0, col="red")
points(time,Ile, pch=0, col="red")
points(time,Leu, pch=0, col="red")
points(time,Lys, pch=0, col="red")
points(time,Met, pch=0, col="red")
points(time,Cys, pch=0, col="red")
points(time,Phe, pch=0, col="red")
points(time,Thr, pch=0, col="red")
points(time,Tyr, pch=0, col="red")
points(time,Val, pch=0, col="red")

points(time,Ammonia, pch=2, col="green")

data3=read.delim("dataFigure2-3.csv", head=TRUE, sep=",")
attach(data3)

plot(time,Ala,xlab="Hours",ylab="mg/L", col="blue", ylim=c(0,600))
l3=c(paste0('                                         Extracellular\n','-NaCl'))
mtext(l3, side=3, line=0, cex=1.5, font=3)
points(time,Asp, pch=1, col="blue")
points(time,Glu, pch=1, col="blue")
points(time,Gln, pch=1, col="blue")
points(time,Ser, pch=1, col="blue")
points(time,Ala, pch=1, col="blue")
points(time,Gly, pch=1, col="blue")
points(time,Arg, pch=1, col="blue")

points(time,His, pch=0, col="red")
points(time,Ile, pch=0, col="red")
points(time,Leu, pch=0, col="red")
points(time,Lys, pch=0, col="red")
points(time,Met, pch=0, col="red")
points(time,Cys, pch=0, col="red")
points(time,Phe, pch=0, col="red")
points(time,Thr, pch=0, col="red")
points(time,Tyr, pch=0, col="red")
points(time,Val, pch=0, col="red")

points(time,Ammonia, pch=2, col="green")

data4=read.delim("dataFigure2-4.csv", head=TRUE, sep=",")
attach(data4)

plot(time,Ala,xlab="Hours",ylab="mg/L", col="blue", ylim=c(0,600))
l4=c(paste0('\n','+NaCl'))
mtext(l4, side=3, line=0, cex=1.5, font=3)

points(time,Asp, pch=1, col="blue")
points(time,Glu, pch=1, col="blue")
points(time,Gln, pch=1, col="blue")
points(time,Ser, pch=1, col="blue")
points(time,Ala, pch=1, col="blue")
points(time,Gly, pch=1, col="blue")
points(time,Arg, pch=1, col="blue")

points(time,His, pch=0, col="red")
points(time,Ile, pch=0, col="red")
points(time,Leu, pch=0, col="red")
points(time,Lys, pch=0, col="red")
points(time,Met, pch=0, col="red")
points(time,Cys, pch=0, col="red")
points(time,Phe, pch=0, col="red")
points(time,Thr, pch=0, col="red")
points(time,Tyr, pch=0, col="red")
points(time,Val, pch=0, col="red")

points(time,Ammonia, pch=2, col="green")

